### ISSUE TITLE
DIV Soup

### ISSUE THREAD

**Issue by WildAndrewLee** [sakibj/sakibj.github.io#1]
Disgusting.

**Comment by sakibj** [comment]
rude

**Comment by sakibj** [comment]
http://www.dirtymarkup.com/ fixed

**Comment by WildAndrewLee** [comment]
I was referring to the fact that you're using html5shiv even though you don't have any HTML5 markup.

**Comment by sakibj** [comment]
It's for internet explorer support
I might use it, experimenting with a bunch of stuff
